language: node_js
node_js: '14'

os: windows

install:
- npm install
- npm audit fix
- npm install react-scripts@4.0.1
- npm install eslint

script:
- npm run-script react-build
- npm run-script build:osx

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "dist/ZombiesHelpStarterContributor-0.1.0-win.zip"
  skip_cleanup: true
  on:
    tags: false
